# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWb7pqY3MljhOu2f4LzYb070y0yb2Y21
"""

pip install tensorflow keras

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
print("Upload fer2013.csv now...")
uploaded = files.upload()  # ← Click and select your fer2013.csv

import pandas as pd
import numpy as np
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D

print("Loading dataset...")
df = pd.read_csv('fer2013.csv')

def prepare_data(df):
    X = np.array([np.fromstring(pix, sep=' ').reshape(48, 48, 1).astype('float32') / 255
                  for pix in df['pixels']])
    y = to_categorical(df['emotion'], 7)
    return X, y

train_df = df[df['Usage'] == 'Training']
val_df = df[df['Usage'] == 'PublicTest']

X_train, y_train = prepare_data(train_df)
X_val, y_val = prepare_data(val_df)

print("Building model...")
model = Sequential([
    Conv2D(64, (3, 3), activation='relu', input_shape=(48, 48, 1)),
    MaxPooling2D(2, 2), Dropout(0.25),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2), Dropout(0.25),
    Conv2D(256, (3, 3), activation='relu'),
    MaxPooling2D(2, 2), Dropout(0.25),
    Flatten(),
    Dense(128, activation='relu'), Dropout(0.5),
    Dense(7, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
print("Training... (10-15 mins on GPU)")
model.fit(X_train, y_train, epochs=30, batch_size=64, validation_data=(X_val, y_val), verbose=1)

model.save('super_emotion_brain.h5')
print("MODEL SAVED! Downloading in 3 seconds...")
from google.colab import files
files.download('super_emotion_brain.h5')